#!/bin/bash
source /home/user/data.txt
docker pull schnitzler/mysqldump
docker run \
    --network shvirtd-example-python_backend \
    --rm --entrypoint "" \
    -v `pwd`/backup:/backup \
    --link="db" \
    schnitzler/mysqldump \
    mysqldump --opt -h 172.20.0.10 -u root -pYtReWq4321 "--result-file=/backup/dumps.sql" virtd
