
#Описание переменных для секретов и рестртов
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped


#Созадние сервиса БД
services:
  db:
    container_name: db
    image: mysql:latest
    networks:
      backend:
        ipv4_address: 172.20.0.10
    <<: [*env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       
  web:
    depends_on: ["db"]
    container_name: web
    build:
      dockerfile:  Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    <<: [*env_file, *restart]
    environment:
      - DB_HOST=db
      - DB_USER=app
      - DB_PASSWORD:${MYSQL_PASSWORD}
      - DB_NAME=example
 
  
#Создание bridge-сети с названием "backend" 172.20.0.0/24
networks:
  backend:
    driver: bridge
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.20.0.0/24
